#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ harold.bjc@gmail.com:/var/www/haroldbjc.work/
echo "Deployment complete"