#!/bin/sh

echo "Switching to branch main..."
git checkout main

echo "Pulling the files..."
git pull

echo "Install node_modules..."
npm install

echo "Building app..."
npm run build

echo "Restarting pm2..."
pm2 restart haroldbjc-work